# Generated by Django 4.2 on 2023-04-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_analytics_remove_project_board_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
