# Generated by Django 4.2 on 2023-04-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0007_alter_project_created_at'),
        ('Projects', '0008_auto_20230427_1251'),
    ]

    operations = [
    ]
