# Generated by Django 4.2 on 2023-04-24 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_board_background_board_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='board_backgrounds/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
