# Generated by Django 4.2 on 2023-04-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_board_background_board_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Open', max_length=100)),
            ],
        ),
    ]
