# Generated by Django 4.2 on 2023-04-24 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AlterField(
            model_name='userissue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.project'),
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='userissue',
            table='user_issue',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
